name: security generic scan
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
jobs:
  executing-secret-scan:
    name: Secret Scan
    if: (github.actor != 'dependabot[bot]')
    uses: pgmfernandes/custom-reusable-action-python/.github/workflows/secret-scan-action.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  executing-sca-scan:
    name: Sca Scan
    if: (github.actor != 'dependabot[bot]')
    uses: pgmfernandes/custom-reusable-action-python/.github/workflows/sca-scan-action.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
