
name: Executing sca scan action

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  get-sca-scan-config:
    name: Config SCA Scannig
    runs-on: ubuntu-latest
    container: python:3.9-buster
    outputs:
      SNYK_SCA_CHECK: ${{ steps.config-pipe-task.outputs.SNYK_SCA_CHECK }}
      SNYK_THRESHOLD_SCA:: ${{ steps.config-pipe-task.outputs.SNYK_THRESHOLD_SCA }}
      SNYK_ORG: ${{ steps.config-pipe-task.outputs.SNYK_ORGSNYK_ORG }}      
    steps:        
      - name: Running config pipeline
        id: config-pipe-task
        run:
         echo "Running sca snyk"
