
name: Executing sca scan action

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  get-secret-scan-config:
    name: Getting scan config
    runs-on: ubuntu-latest
    container: python:3.9-buster
    outputs:
      TRIVY_SCA_CHECK: ${{ steps.config-pipe-task.outputs.SEMGREP_CHECK }}
      TRIVY_SCA_THRESHOLD:: ${{ steps.config-pipe-task.outputs.SEMGREP_CHECK }}
      SNYK_SCA_CHECK: ${{ steps.config-pipe-task.outputs.TRIVY_SECRET_CHECK }}
      SNYK_SCA_THRESHOLD: ${{ steps.config-pipe-task.outputs.GITLEAKS_CHECK }}
    steps:        
      - name: Running config pipeline
        id: config-pipe-task
        uses: pgmfernandes/secret-scan-action-config@main
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
