name: Executing secret scan action

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  get-secret-scan-config:
    name: Getting scan config
    runs-on: ubuntu-latest
    container: python:3.9-buster
    outputs:
      SEMGREP_CHECK: ${{ steps.config-pipe-task.outputs.SEMGREP_CHECK }}
      TRIVY_SECRET_CHECK: ${{ steps.config-pipe-task.outputs.TRIVY_SECRET_CHECK }}
      TRIVY_SECRET_THRESHOLD: ${{ steps.config-pipe-task.outputs.TRIVY_SECRET_THRESHOLD }}
      TRIVY_SECRET_SECRET_CONFIG: ${{ steps.config-pipe-task.outputs.TRIVY_SECRET_SECRET_CONFIG }}
      GITLEAKS_CHECK: ${{ steps.config-pipe-task.outputs.GITLEAKS_CHECK }}
    steps:        
      - name: Running config pipeline
        id: config-pipe-task
        uses: pgmfernandes/setup-pipeline-action@main
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
