name: Executing secret scan action

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      SEMGREP_CHECK:
        required: false
        type: boolean
        default: false
      SEMGREP_SECRET_CONFIG:
        required: false
        type: string
      GITLEAKS_CHECK:
        required: false
        type: boolean
        default: false
      GITLEAKS_SECRET_CONFIG:
        required: false
        type: string
      TRIVY_SECRET_CHECK:
        required: false
        type: boolean
        default: false
      TRIVY_SECRET_THRESHOLD:
        required: false
        type: string
        default: 'high'
      TRIVY_SECRET_SECRET_CONFIG:
        required: false
        type: string
jobs:
  execute-semgrep-scan:
      name: Secret Semgrep
      runs-on: ubuntu-latest
      if:  ${{ inputs.SEMGREP_CHECK == 'True' }}
      steps:
        - name: Semgrep enabled
          run: | 
            echo "Semgrep is enabled ${{ inputs.SEMGREP_CHECK }}"
            
  execute-gitleak-scan:
      name: Gitleaks scan
      runs-on: ubuntu-latest
      if:  ${{ inputs.GITLEAKS_CHECK == 'True' }}
      steps:
        - name: Gitleaks enabled
          run: | 
            echo "Gitleaks is enabled ${{ inputs.GITLEAKS_CHECK }}"
            
  execute-trivy-scan:
      needs: get-secret-scan-config
      name: Trivy Secret Scan
      runs-on: ubuntu-latest
      if:  ${{ inputs.TRIVY_SECRET_CHECK == 'True' }}
      steps: 
        - id: running-scan
          name: Running trivy action
          uses: pgmfernandes/trivy-secret-scan-action@main
          with:
            severity: ${{ inputs.TRIVY_SECRET_THRESHOLD }}
            ignore-policy: ${{ inputs.TRIVY_SECRET_SECRET_CONFIG }}
